version: 2
updates:
  # Update GitHub actions
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: saturday
    commit-message:
      prefix: ci
    labels:
      - dependencies
  # Update Go dependencies
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: gomod
    schedule:
      interval: weekly
      day: saturday
    commit-message:
      prefix: build
    labels:
      - dependencies
