codecov:
  notify:
    wait_for_ci: false
coverage:
  range: 50..90
  round: nearest
  precision: 2
  status:
    project:
      default:
        target: 60%
    patch:
      default:
        target: 60%
comment:
  layout: header,reach,diff,flags,files,footer
  require_changes: false
ignore:
  - packages/eagle/internal/**
flags:
  dymant:
    paths:
      - packages/dymant/**
    carryforward: true
  eagle:
    paths:
      - packages/eagle/**
    ignore:
      - packages/eagle/internal/**
    carryforward: true
