coverage:
  range: 30..90
  round: nearest
  precision: 2
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto
comment:
  layout: header,reach,diff,flags,files,footer
  require_changes: false
ignore:
  - packages/eagle/internal/**
flags:
  dymant:
    paths:
      - packages/dymant/**
    carryforward: true
  eagle:
    paths:
      - packages/eagle/**
    carryforward: true
