codecov:
  branch: main
coverage:
  range: 30..70
  round: nearest
  precision: 2
  status:
    project:
      default:
        target: auto
      main:
        branches:
          - main
        if_ci_failed: success
    patch:
      default:
        target: auto
      main:
        branches:
          - main
        if_ci_failed: success
comment:
  layout: header,reach,diff,flags,files,footer
  require_changes: false
flag_management:
  default_rules:
    carryforward: true
