name: Go Testing
description: Test Go code and optionally upload coverage to codecov.

inputs:
  path:
    description: The path to the package to test.
    required: true
  flag:
    description: The flag to use for codecov. Coverage is not uploaded if left empty.
    default: ""
  tags:
    description: Tags to pass to `go test`.
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Run tests
      shell: bash
      run: |
        go test ./${{ inputs.path }}/... \
          -tags "${{ inputs.tags }}" \
          -race \
          -coverprofile=coverage.out \
          -covermode=atomic \
          -coverpkg=./${{ inputs.path }}/...
    - name: Upload to codecov
      if: inputs.flag != ''
      uses: codecov/codecov-action@v3
      with:
        files: coverage.out
        flags: ${{ inputs.flag }}
