kafka:
  id: instance-manager
  bootstrapServers:
    - localhost:9092
  topic: instance-manager.v1.instances
components:
  minion:
    reservations:
      memory: 256Mi
    extraDisks:
      - name: dunno
        sizePerCpu: 1Gi
    metadata: {}
    aws:
      boot:
        diskSize: 20Gi
        amis:
          - config:
              owner: "164347396974"
              selector:
                Application: taskfleet
                Environment: taskfleet-dev
      network:
        vpcSelector:
          Application: taskfleet
          Environment: taskfleet-dev
        securityGroupSelector:
          Application: taskfleet
          Environment: taskfleet-dev
      iam:
        instanceProfile: TaskfleetMinion
    gcp:
      boot:
        diskSize: 20Gi
        imageLinks:
          - config: https://www.googleapis.com/compute/v1/projects/borchero-com/global/images/taskfleet-instance-manager-testserver
      network:
        name: taskfleet-global-vpc
        tags:
          - taskfleet-minion
      iam:
        serviceAccountEmail: taskfleet-minion@borchero-com.iam.gserviceaccount.com
