name: Chore
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: write

jobs:
  conventional-commit:
    name: Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - name: Check valid conventional commit message
        id: lint
        uses: amannn/action-semantic-pull-request@v5
        with:
          subjectPattern: ^(?![A-Z]).+$ # subject should not start with uppercase letter
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Post comment about invalid PR title
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: conventional-commit-pr-title
          message: |
            Thank you for opening this pull request! 👋🏼

            This repository requires pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            <details><summary>**Details**</summary>

            ```
            ${{ steps.lint.outputs.error_message }}
            ```

            </details>
      - name: Delete comment about invalid PR title
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: conventional-commit-pr-title
          delete: true

  release-drafter:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels based on conventional commits
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
