name: CI - gRPC
on:
  pull_request:
    paths:
      - "**/*.proto"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  check-breaking:
    name: Check Breaking Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
      - name: Check for breaking changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: https://github.com/taskfleet/taskfleet.git#branch=main
