name: CI - Package Mercury
on:
  pull_request:
    paths:
      - packages/mercury/**
      - .github/workflows/pkg-mercury.yml
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/actions/go-test
        with:
          flag: mercury
          path: packages/mercury
