name: gRPC Schema
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: read

jobs:
  publish:
    name: Publish to Buf Schema Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Push schema
        uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_API_TOKEN }}
          input: grpc/schema
