name: gRPC Schema Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    name: Publish gRPC Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Push schema
        uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_API_TOKEN }}
          input: grpc/schema
