name: Package Dymant
on:
  pull_request:
    paths:
      - packages/dymant/**
      - packages/eagle/**
      - .github/workflows/pkg-dymant.yml
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run linting
        uses: ./.github/actions/go-lint
        with:
          path: packages/dymant

  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      kafka:
        image: bitnami/kafka:3.3.1
        env:
          KAFKA_ENABLE_KRAFT: yes
          KAFKA_CFG_PROCESS_ROLES: broker,controller
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
          KAFKA_BROKER_ID: 1
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
          ALLOW_PLAINTEXT_LISTENER: yes
        ports:
          - 9092:9092
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Wait for Kafka
        run: |
          until docker logs "${{ job.services.kafka.id }}" 2>&1 | \
            grep -q "Kafka Server started (kafka.server.KafkaRaftServer)"; do sleep 10; done
      - name: Run tests
        uses: ./.github/actions/go-test
        with:
          flag: dymant
          path: packages/dymant
        env:
          KAFKA_BOOTSTRAP_SERVER: localhost:9092
