name: Package Jack
on:
  pull_request:
    paths:
      - packages/jack/**
      - .github/workflows/pkg-jack.yaml
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Lint Code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          working-directory: packages/jack

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run Tests
        run: |
          go test ./packages/jack/... \
            -race \
            -coverprofile=coverage.out \
            -covermode=atomic \
            -coverpkg=./packages/jack/...
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
          flags: jack
