name: Package Eagle
on:
  pull_request:
    paths:
      - packages/eagle/**
      - .github/workflows/pkg-eagle.yml
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  lint:
    name: Lint Eagle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run linting
        uses: ./.github/actions/go-lint
        with:
          path: packages/eagle

  test:
    name: Test Eagle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        uses: ./.github/actions/go-test
        with:
          path: packages/eagle
          flag: eagle
