name: Service Genesis - Integration
on:
  pull_request:
    types:
      - labeled
    paths:
      - services/genesis/**
      - packages/dymant/**
      - packages/eagle/**
      - packages/jack/**
      - packages/mercury/**
      - packages/postgres/**
      - .github/workflows/svc-genesis-integration.yml
  push:
    branches:
      - main

# Cannot cancel in-progress since external resources must be torn down by the test
permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Integration Test Genesis
    if: github.event.label.name == 'integration-test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate with GCP
        id: gcp-auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Run tests
        uses: ./.github/actions/go-test
        with:
          path: services/genesis/internal
          tags: integration
          flag: genesis
        env:
          GCP_PROJECT: ${{ steps.gcp-auth.outputs.project_id }}
